#!/bin/bash
echo search keyword: $1
echo Mat ; cat Mat.txt | grep $1
echo Mak ; cat Mak.txt | grep $1
echo Luk ; cat Luk.txt | grep $1
echo Jhn ; cat Jhn.txt | grep $1
echo Act ; cat Act.txt | grep $1
echo Rom ; cat Rom.txt | grep $1
echo 1Co ; cat 1Co.txt | grep $1
echo 2Co ; cat 2Co.txt | grep $1
echo Gal ; cat Gal.txt | grep $1
echo Eph ; cat Eph.txt | grep $1
echo Phl ; cat Phl.txt | grep $1
echo Col ; cat Col.txt | grep $1
echo 1Ts ; cat 1Ts.txt | grep $1
echo 2Ts ; cat 2Ts.txt | grep $1
echo 1Ti ; cat 1Ti.txt | grep $1
echo 2Ti ; cat 2Ti.txt | grep $1
echo Tit ; cat Tit.txt | grep $1
echo Phm ; cat Phm.txt | grep $1
echo Heb ; cat Heb.txt | grep $1
echo Jas ; cat Jas.txt | grep $1
echo 1Pe ; cat 1Pe.txt | grep $1
echo 2Pe ; cat 2Pe.txt | grep $1
echo 1Jn ; cat 1Jn.txt | grep $1
echo 2Jn ; cat 2Jn.txt | grep $1
echo 3Jn ; cat 3Jn.txt | grep $1
echo Jud ; cat Jud.txt | grep $1
echo Rev ; cat Rev.txt | grep $1
