#!/bin/bash
echo search keyword: $1
echo Gen ; cat Gen.txt | grep $1
echo Exo ; cat Exo.txt | grep $1
echo Lev ; cat Lev.txt | grep $1
echo Num ; cat Num.txt | grep $1
echo Deu ; cat Deu.txt | grep $1
echo Jos ; cat Jos.txt | grep $1
echo Jug ; cat Jug.txt | grep $1
echo 1Sa ; cat 1Sa.txt | grep $1
echo 2Sa ; cat 2Sa.txt | grep $1
echo 1Ki ; cat 1Ki.txt | grep $1
echo 2Ki ; cat 2Ki.txt | grep $1
echo Isa ; cat Isa.txt | grep $1
echo Jer ; cat Jer.txt | grep $1
echo Eze ; cat Eze.txt | grep $1
echo Hos ; cat Hos.txt | grep $1
echo Joe ; cat Joe.txt | grep $1
echo Amo ; cat Amo.txt | grep $1
echo Oba ; cat Oba.txt | grep $1
echo Jon ; cat Jon.txt | grep $1
echo Mic ; cat Mic.txt | grep $1
echo Nah ; cat Nah.txt | grep $1
echo Hab ; cat Hab.txt | grep $1
echo Zep ; cat Zep.txt | grep $1
echo Hag ; cat Hag.txt | grep $1
echo Zec ; cat Zec.txt | grep $1
echo Mal ; cat Mal.txt | grep $1
echo Psa ; cat Psa.txt | grep $1
echo Pro ; cat Pro.txt | grep $1
echo Job ; cat Job.txt | grep $1
echo Son ; cat Son.txt | grep $1
echo Rut ; cat Rut.txt | grep $1
echo Lam ; cat Lam.txt | grep $1
echo Ecc ; cat Ecc.txt | grep $1
echo Est ; cat Est.txt | grep $1
echo Dan ; cat Dan.txt | grep $1
echo Ezr ; cat Ezr.txt | grep $1
echo Neh ; cat Neh.txt | grep $1
echo 1Ch ; cat 1Ch.txt | grep $1
echo 2Ch ; cat 2Ch.txt | grep $1
